-- MySQL Script generated by MySQL Workbench
-- Thu Jun  9 16:11:57 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ebdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ebdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ebdb` DEFAULT CHARACTER SET utf8 ;
USE `ebdb` ;

-- -----------------------------------------------------
-- Table `ebdb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebdb`.`User` (
  `userid` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Admin` TINYINT(1) NOT NULL,
  `Blocked` TINYINT(1) NOT NULL,
  `Nickname` VARCHAR(45) NOT NULL,
  `Profilepic` TINYTEXT NOT NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`Node`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebdb`.`Node` (
  `NodeID` VARCHAR(45) NOT NULL,
  `revision` INT(11) NOT NULL,
  `Groupname` VARCHAR(45) NOT NULL,
  `ParentNode` VARCHAR(45) NULL DEFAULT NULL,
  `Content` MEDIUMTEXT NULL DEFAULT NULL,
  `vote_status` ENUM('inactive', 'wait', 'approve') NOT NULL,
  `TimeWritten` DATETIME NOT NULL,
  `writer` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`NodeID`),
  INDEX `fk_Node_Group1_idx` (`Groupname` ASC),
  INDEX `fk_Node_User1_idx` (`writer` ASC),
  CONSTRAINT `fk_Node_Group1`
    FOREIGN KEY (`Groupname`)
    REFERENCES `ebdb`.`RenoGroup` (`Groupname`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Node_User1`
    FOREIGN KEY (`writer`)
    REFERENCES `ebdb`.`User` (`userid`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`RenoGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebdb`.`RenoGroup` (
  `Groupname` VARCHAR(45) NOT NULL,
  `Genre` VARCHAR(45) NOT NULL,
  `VoteLimit` TIME NOT NULL,
  `WriteLimit` TIME NOT NULL,
  `readers` INT(11) NOT NULL,
  `writers` INT(11) NOT NULL,
  `WriterLimit` INT(11) NOT NULL,
  `CurrentNode` VARCHAR(45) NULL DEFAULT NULL,
  `Finished` TINYINT(1) NOT NULL,
  `AllowRollback` TINYINT(1) NOT NULL,
  `GroupImageURL` VARCHAR(45) NOT NULL,
  `createtime` DATETIME NOT NULL,
  `writerchanged` TINYINT(1) NOT NULL,
  `writerchangetime` DATETIME NOT NULL,
  `writer` VARCHAR(45) NULL DEFAULT NULL,
  `creator` VARCHAR(45) NOT NULL,
  `minwrite` INT(11) NOT NULL,
  `maxwrite` INT(11) NOT NULL,
  PRIMARY KEY (`Groupname`),
  INDEX `fk_Group_Node1_idx` (`CurrentNode` ASC),
  INDEX `fk_Group_User1_idx` (`writer` ASC),
  INDEX `fk_Group_User2_idx` (`creator` ASC),
  CONSTRAINT `fk_Group_Node1`
    FOREIGN KEY (`CurrentNode`)
    REFERENCES `ebdb`.`Node` (`NodeID`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Group_User1`
    FOREIGN KEY (`writer`)
    REFERENCES `ebdb`.`User` (`userid`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Group_User2`
    FOREIGN KEY (`creator`)
    REFERENCES `ebdb`.`User` (`userid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`JoinGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebdb`.`JoinGroup` (
  `Groupname` VARCHAR(45) NOT NULL,
  `isWriter` TINYINT(1) NOT NULL,
  `userid` VARCHAR(45) NOT NULL,
  INDEX `fk_JoinGroup_Group1_idx` (`Groupname` ASC),
  INDEX `fk_JoinGroup_User1_idx` (`userid` ASC),
  CONSTRAINT `fk_JoinGroup_Group1`
    FOREIGN KEY (`Groupname`)
    REFERENCES `ebdb`.`RenoGroup` (`Groupname`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JoinGroup_User1`
    FOREIGN KEY (`userid`)
    REFERENCES `ebdb`.`User` (`userid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`Vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebdb`.`Vote` (
  `VoteID` INT(11) NOT NULL AUTO_INCREMENT,
  `Group_GroupId` VARCHAR(45) NOT NULL,
  `Votetype` ENUM('add', 'change', 'rollback', 'finish') NOT NULL,
  `NodeId` VARCHAR(45) NOT NULL,
  `StartTime` DATETIME NOT NULL,
  `EndTime` DATETIME NOT NULL,
  `VoteStatus` TINYINT(1) NOT NULL,
  `ModifyNode` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`VoteID`),
  INDEX `fk_Vote_Group1_idx` (`Group_GroupId` ASC),
  INDEX `fk_Vote_Node1_idx` (`NodeId` ASC),
  INDEX `fk_Vote_Node1_idx1` (`ModifyNode` ASC),
  CONSTRAINT `fk_Vote_Group1`
    FOREIGN KEY (`Group_GroupId`)
    REFERENCES `ebdb`.`RenoGroup` (`Groupname`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vote_Node1`
    FOREIGN KEY (`NodeId`)
    REFERENCES `ebdb`.`Node` (`NodeID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`Voting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebdb`.`Voting` (
  `Vote_VoteID` INT(11) NOT NULL,
  `Vote_Value` ENUM('yes', 'no', 'novote') NOT NULL,
  `userid` VARCHAR(45) NOT NULL,
  INDEX `fk_Voting_Vote1_idx` (`Vote_VoteID` ASC),
  INDEX `fk_Voting_User1_idx` (`userid` ASC),
  CONSTRAINT `fk_Voting_User1`
    FOREIGN KEY (`userid`)
    REFERENCES `ebdb`.`User` (`userid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voting_Vote1`
    FOREIGN KEY (`Vote_VoteID`)
    REFERENCES `ebdb`.`Vote` (`VoteID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
